### ISSUE TITLE
DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead

### ISSUE THREAD

**Issue by oppytut** [ericclemmons/reload-server-webpack-plugin#8]
![screenshot_20180601_093838](https://user-images.githubusercontent.com/11549752/40818091-aa840a16-657f-11e8-82ab-2b5a3bed12db.png)

Deprecation warning when use ReloadServerPlugin in Webpack 4.9.1

**Comment by Rita-xrr** [comment]
请求这个问题怎么解决的

**Comment by oppytut** [comment]
@Rita-xrr, I do not know. However, I think reload-server-webpack-plugin works fine.
@ericclemmons

**Comment by sibelius** [comment]
fixed here https://github.com/ericclemmons/reload-server-webpack-plugin/pull/9
